name: Build and deploy Node.js app to Azure Web App - mr-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Cambié ubuntu-latest a una versión específica

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3 # Cambié v1 a v3
        with:
          node-version: '16.x'

      - name: Instalar dependencias, construir y testear
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Subir artefacto para despliegue
        uses: actions/upload-artifact@v4 # Actualizado a v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-22.04  # Cambié ubuntu-latest a una versión específica
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Descargar artefacto del job de construcción
        uses: actions/download-artifact@v4 # Actualizado a v4
        with:
          name: node-app

      - name: Desplegar en Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: mr-app-bya3dmg0bwfxdmcd
          slot-name: 'production' # Debe ser "production" en minúsculas
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_711763FDD8894F33B4AFA1AD1732C2EA }}
          package: .